
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Job_portal.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company_tb
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Company_tb()
    {

        this.ApplyJob_tb = new HashSet<ApplyJob_tb>();

        this.PostJob_tb = new HashSet<PostJob_tb>();

    }


    public int CID { get; set; }
    

    [Required(ErrorMessage ="Company Name Required")]
    [Display(Name ="Company Name")]


    public string CNAME { get; set; }

    [Required(ErrorMessage = "Address is Required")]
    

    public string Address { get; set; }

    [Required(ErrorMessage ="City Required")]


    public string City { get; set; }
    [Required(ErrorMessage ="State is Required")]
    

    public string State { get; set; }
    [Required(ErrorMessage ="Contact Name is Required")]
    [Display(Name ="Contact Person")]

    public string ContactPerson { get; set; }
    [Required(ErrorMessage ="Mobile Number is Required")]
    [Display(Name ="Mobile Number")]

    public string MobileNo { get; set; }
    [Required(ErrorMessage ="Contact Number Required")]
    [Display(Name ="Contact Number")]

    public string ContactNumber { get; set; }
    [Required(ErrorMessage ="Email is Required")]
    //[Display(Name ="Company Name")]

    public string Email { get; set; }
    [Required(ErrorMessage ="User Name is Required")]
    [Display(Name ="User Name")]

    public string UserName { get; set; }
    [Required(ErrorMessage ="Password is Required")]
    //[Display(Name ="Company Name")]

    public string Password { get; set; }
    [Required(ErrorMessage ="Website is Required")]
    [Display(Name ="Company Website")]

    public string Website { get; set; }
    

    public Nullable<System.DateTime> EntryDate { get; set; }

    public Nullable<int> Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ApplyJob_tb> ApplyJob_tb { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PostJob_tb> PostJob_tb { get; set; }

}

}
